/*
 * Copyright (C) 2013, The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * !!!!! DO NOT EDIT THIS FILE !!!!!
 *
 * This file was generated from
 *   dictionary/structure/v4/content/dict_content.h
 */

#ifndef LATINIME_BACKWARD_V402_DICT_CONTENT_H
#define LATINIME_BACKWARD_V402_DICT_CONTENT_H

#include "defines.h"

namespace latinime {
namespace backward {
namespace v402 {

class DictContent {
 public:
    virtual ~DictContent() {}
    virtual bool isValid() const = 0;

 protected:
    DictContent() {}

 private:
    DISALLOW_COPY_AND_ASSIGN(DictContent);
};
} // namespace v402
} // namespace backward
} // namespace latinime
#endif /* LATINIME_BACKWARD_V402_DICT_CONTENT_H */
