# CI: Build unsigned APK (release) and optional signing
# Place at: .github/workflows/build-unsigned-apk.yml
#
# Features:
# - configurable module (default: app)
# - builds release APK as unsigned by passing -PskipSigning=true
# - caches Gradle
# - installs minimal Android commandline tools + platform-tools + build-tools
# - uploads unsigned APK artifact
# - optional signing step using RELEASE_KEYSTORE_BASE64 + secrets (safe: decoded only in runner)
# - simple retry for SDK install commands to mitigate transient network failures
#
# Secrets recommended (optional):
# - RELEASE_KEYSTORE_BASE64 (base64 of keystore.jks) - optional, if present workflow will sign
# - RELEASE_KEY_ALIAS
# - RELEASE_STORE_PASS
# - RELEASE_KEY_PASS
#
# Inputs for manual dispatch:
# - module: module path (default "app")
# - buildType: release/debug (default "release")
# - skipSigningProp: property passed to Gradle to skip signing (default "true")
#
name: Build Release APK (unsigned & optional signing)

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module directory containing the Android app (e.g., app)'
        required: false
        default: 'app'
      buildType:
        description: 'Build type to assemble (release/debug)'
        required: false
        default: 'release'
      skipSigningProp:
        description: 'Gradle property value to skip signing (use with -PskipSigning=VALUE)'
        required: false
        default: 'true'
  push:
    branches:
      - main
      - master

env:
  ANDROID_SDK_ROOT: /usr/local/share/android-sdk
  BUILD_TOOLS_VERSION: '34.0.0'
  PLATFORM_VERSION: 'android-34'
  GRADLE_USER_HOME: ${{ runner.temp }}/.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK command-line tools and build-tools (with retry)
        shell: bash
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          set -euo pipefail
          attempts=0
          max_attempts=3
          until [ "$attempts" -ge "$max_attempts" ]
          do
            attempts=$((attempts+1))
            echo "SDK install attempt $attempts/$max_attempts"
            mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
            cd "$ANDROID_SDK_ROOT/cmdline-tools"
            # download a stable commandlinetools bundle; fallback to a known version
            if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
              curl -sS -o cmd.zip "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip" || { echo "curl failed"; rm -f cmd.zip || true; sleep 5; continue; }
              unzip -q cmd.zip -d tmpcmd || { echo "unzip failed"; rm -f cmd.zip || true; sleep 5; continue; }
              rm -f cmd.zip
              mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
              mv tmpcmd/cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
              rm -rf tmpcmd || true
            fi
            export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
            yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;${{ env.PLATFORM_VERSION }}" "build-tools;${{ env.BUILD_TOOLS_VERSION }}" && break
            echo "sdkmanager failed, retrying in 5s..."
            sleep 5
          done

      - name: Show environment info
        run: |
          java -version
          echo "Android SDK: $ANDROID_SDK_ROOT"
          "$ANDROID_SDK_ROOT/platform-tools/adb" version || true
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --list || true

      - name: Assemble APK (unsigned) - clean then assemble
        env:
          MODULE: ${{ github.event.inputs.module || 'app' }}
          BUILD_TYPE: ${{ github.event.inputs.buildType || 'release' }}
          SKIP_SIGNING_PROP: ${{ github.event.inputs.skipSigningProp || 'true' }}
        run: |
          set -euo pipefail
          echo "Module: $MODULE"
          echo "Build type: $BUILD_TYPE"
          # Build task (e.g., assembleRelease or assembleDebug)
          TASK="assemble${BUILD_TYPE^}"
          # Use skipSigning prop so projects that support -PskipSigning will avoid applying signingConfig
          ./gradlew -p "$MODULE" clean "$TASK" -PskipSigning="$SKIP_SIGNING_PROP" --no-daemon -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Find unsigned APK(s)
        id: find_apk
        env:
          MODULE: ${{ github.event.inputs.module || 'app' }}
          BUILD_TYPE: ${{ github.event.inputs.buildType || 'release' }}
        run: |
          set -euo pipefail
          MODULE_DIR="${MODULE}"
          BUILD_TYPE_LOWER=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
          # Common outputs path
          APK_DIR="${MODULE_DIR}/build/outputs/apk/${BUILD_TYPE_LOWER}"
          echo "Looking for apk in $APK_DIR"
          # prefer "*-release-unsigned.apk" pattern; fallback to any apk
          APK_FILE=$(find "$APK_DIR" -maxdepth 2 -type f -iname "*${BUILD_TYPE_LOWER}*-unsigned.apk" | head -n1 || true)
          if [ -z "$APK_FILE" ]; then
            APK_FILE=$(find "$APK_DIR" -maxdepth 2 -type f -iname "*.apk" | head -n1 || true)
          fi
          if [ -z "$APK_FILE" ]; then
            echo "No APK found in $APK_DIR"
            exit 1
          fi
          echo "Unsigned APK: $APK_FILE"
          echo "::set-output name=apk::$APK_FILE"

      - name: Upload unsigned APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: ${{ steps.find_apk.outputs.apk }}

      - name: Optionally sign APK (if keystore provided)
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
        env:
          MODULE: ${{ github.event.inputs.module || 'app' }}
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
        run: |
          set -euo pipefail
          # decode keystore from secret
          TMP_DIR="$(mktemp -d)"
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > "$TMP_DIR/keystore.jks"
          KS="$TMP_DIR/keystore.jks"
          ALIAS="${{ secrets.RELEASE_KEY_ALIAS }}"
          STORE_PASS="${{ secrets.RELEASE_STORE_PASS }}"
          KEY_PASS="${{ secrets.RELEASE_KEY_PASS }}"
          APK_PATH="${{ steps.find_apk.outputs.apk }}"
          if [ -z "$APK_PATH" ]; then
            echo "APK path not found"; exit 1
          fi
          SIGNED_APK="${APK_PATH%.apk}-signed.apk"
          APKSIGNER="${ANDROID_SDK_ROOT}/build-tools/${BUILD_TOOLS_VERSION}/apksigner"
          if [ ! -x "$APKSIGNER" ]; then
            echo "apksigner not found at $APKSIGNER"; exit 1
          fi
          echo "Signing APK (output: $SIGNED_APK)..."
          "$APKSIGNER" sign --ks "$KS" --ks-key-alias "$ALIAS" --ks-pass "pass:$STORE_PASS" --key-pass "pass:$KEY_PASS" --out "$SIGNED_APK" "$APK_PATH"
          echo "Signed APK written to $SIGNED_APK"
          # Upload signed artifact
          echo "::set-output name=signed_apk::$SIGNED_APK"
        shell: bash

      - name: Upload signed APK (if created)
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: ${{ steps.build.outputs.signed_apk || steps.find_apk.outputs.apk }}
