name: Feature request / Suggestion
description: Suggest an idea for this project
labels:
  - "proposal"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your help in making FlorisBoard better!

        Guide to a good feature-request:
        • Please search existing proposals to avoid creating duplicates.
        • If you have multiple ideas which are not directly connected to other, file a new issue for each idea. This makes it easier to implement your proposals.
        • Describe your idea in a short but concise way.
        • If you have any examples, e.g. screenshots or other keyboards have the proposed feature implemented, feel free to post them after your description.
  - type: textarea
    id: feature
    attributes:
      label: Feature idea
      description: Please explain your idea in a precise way.
    validations:
      required: true
